export const products = [
    { id: 1, name: 'Product A', price: 10, description: 'Description A', image: '/img/a.jpg' },
    { id: 2, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 3, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 4, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 5, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 6, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 7, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 8, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 9, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 10, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 11, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 12, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 13, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 14, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 15, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 16, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 17, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 18, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 19, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 20, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 21, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 22, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 23, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 24, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 25, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 26, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 27, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 28, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
    { id: 29, name: 'Product B', price: 20, description: 'Description B', image: '/img/b.jpg' },
  ];
  